project:
  type: website

website:
  title: "BiocKudos"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kevinrue/BiocKudos
format:
  html:
    theme: cosmo
    css: styles.css



